spring.application.name=photovault

spring.datasource.url=jdbc:postgresql://localhost:5432/photovault
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway - auto runs migration SQL files
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Let Flyway handle table creation, not Hibernate
spring.jpa.hibernate.ddl-auto=validate
